#!/bin/bash
# ~~~ Indexing the Transcriptome ~~~ #
kallisto index -i alignment_free/reference_index.idx data/transcripts.fna

# ~~~ Quantifying Synthetic Reads ~~~ #
# Directory containing the synthetic reads generated by Polyester
READ_DIR="polyester_reads"

mkdir -p alignment_free

# Declare conditions, error levels, and replicates
conditions=("control" "treatment")
error_levels=("low" "medium" "high")
replicates=("01" "02" "03")

# Loop through conditions, error levels, and replicates
for condition in "${conditions[@]}"; do
    for error_level in "${error_levels[@]}"; do
        for rep in "${replicates[@]}"; do
            # Construct the input file names based on condition, error level, and replicate
            input_file_1="polyester_reads/${condition}_${error_level}/shuffled_sample_${rep}_1.fasta"
            input_file_2="polyester_reads/${condition}_${error_level}/shuffled_sample_${rep}_2.fasta"
            
            # Construct the output directory name based on condition, error level, and replicate
            output_dir="alignment_free/${condition}_${error_level}_${rep}"
            
            # Run Kallisto quantification
            kallisto quant -i alignment_free/reference_index.idx -o $output_dir -b 100 $input_file_1 $input_file_2
        done
    done
done